-- Core mobility data. Run after 001_initial_schema.sql in Supabase.
create type public.vehicle_kind as enum ('BIKE','CAR','SUV','AUTO','VAN','EV','OTHER');
create type public.verification_state as enum ('NOT_VERIFIED','PENDING','VERIFIED','FAILED','EXPIRED','REJECTED');
create type public.ride_state as enum ('PUBLISHED','BOOKING_PENDING','CONFIRMED','DRIVER_ARRIVING','STARTED','COMPLETED','CANCELLED','FULL');
create type public.booking_state as enum ('PENDING_PAYMENT','CONFIRMED','CANCELLED','COMPLETED','REFUNDED','NO_SHOW');
create table public.cities(id uuid primary key default gen_random_uuid(),name text not null unique,state text not null,country text not null default 'India',latitude numeric,longitude numeric,is_active boolean not null default true,created_at timestamptz not null default now());
create table public.location_zones(id uuid primary key default gen_random_uuid(),city_id uuid not null references public.cities(id),name text not null,description text,latitude numeric,longitude numeric,display_order integer not null default 0,is_active boolean not null default true,unique(city_id,name));
create table public.vehicle_types(id uuid primary key default gen_random_uuid(),kind public.vehicle_kind not null unique,label text not null,rate_per_km numeric(10,2) not null check(rate_per_km>=0),minimum_fare numeric(10,2) not null default 0,maximum_passengers integer not null check(maximum_passengers>0),platform_fee numeric(10,2) not null default 0,cancellation_fee numeric(10,2) not null default 0,is_active boolean not null default true);
create table public.drivers(id uuid primary key references public.profiles(id) on delete cascade,licence_status public.verification_state not null default 'NOT_VERIFIED',identity_status public.verification_state not null default 'NOT_VERIFIED',created_at timestamptz not null default now());
create table public.vehicles(id uuid primary key default gen_random_uuid(),driver_id uuid not null references public.drivers(id),vehicle_type_id uuid not null references public.vehicle_types(id),registration_number text not null unique,make text,model text,color text,capacity integer not null check(capacity>0),verification_status public.verification_state not null default 'PENDING',created_at timestamptz not null default now());
create table public.rides(id uuid primary key default gen_random_uuid(),driver_id uuid not null references public.drivers(id),origin_zone_id uuid not null references public.location_zones(id),destination_zone_id uuid not null references public.location_zones(id),vehicle_id uuid not null references public.vehicles(id),departure_time timestamptz not null,available_seats integer not null check(available_seats>=0),booked_seats integer not null default 0 check(booked_seats>=0),distance_km numeric(10,2),status public.ride_state not null default 'PUBLISHED',created_at timestamptz not null default now(),check(booked_seats<=available_seats));
create table public.bookings(id uuid primary key default gen_random_uuid(),ride_id uuid not null references public.rides(id),passenger_id uuid not null references public.profiles(id),seats integer not null default 1 check(seats>0),status public.booking_state not null default 'PENDING_PAYMENT',booking_distance_km numeric(10,2),booking_rate_per_km numeric(10,2),booking_final_fare numeric(10,2),created_at timestamptz not null default now(),unique(ride_id,passenger_id));
create index rides_search_idx on public.rides(origin_zone_id,destination_zone_id,departure_time) where status='PUBLISHED'; create index zones_city_idx on public.location_zones(city_id); create index bookings_passenger_idx on public.bookings(passenger_id,created_at desc);
alter table public.cities enable row level security; alter table public.location_zones enable row level security; alter table public.vehicle_types enable row level security; alter table public.rides enable row level security; alter table public.bookings enable row level security;
create policy "public active cities" on public.cities for select using(is_active); create policy "public active zones" on public.location_zones for select using(is_active); create policy "public active vehicle types" on public.vehicle_types for select using(is_active); create policy "public published rides" on public.rides for select using(status='PUBLISHED' or driver_id=auth.uid()); create policy "passengers access own bookings" on public.bookings for select using(passenger_id=auth.uid());
insert into public.cities(name,state,latitude,longitude) values ('Indore','Madhya Pradesh',22.7196,75.8577),('Dewas','Madhya Pradesh',22.9676,76.0534) on conflict(name) do nothing;
insert into public.vehicle_types(kind,label,rate_per_km,maximum_passengers) values ('BIKE','Bike',2.50,1),('CAR','Car',4.50,4) on conflict(kind) do nothing;
insert into public.location_zones(city_id,name,display_order) select c.id,z.name,z.ord from public.cities c cross join (values ('Gulawat Lotus Valley',1),('Dewas Naka / Niranjanpur',2),('Sukhlia & Vijay Nagar',3),('Bapat Square & MR-10 Crossing',4),('Super Corridor / ISBT',5),('LIG Circle & Anoop Nagar',6),('Janpath & Chappan Dukan',7),('Palasia Square & High Court',8),('Gandhi Hall & MG Road',9),('Regal Square & Central Museum',10),('Bada Ganpati & Krishnapura Chhatris',11),('Rajwada Palace & Sarafa Bazaar',12),('Kanch Mandir & Itwaria Bazaar',13),('Indore Railway Station / Sarwate Bus Stand',14),('Navlakha Square & Kamla Nehru Prani Sangrahalay',15),('Annapurna Temple & Moti Tabela',16),('Lal Bagh Palace & Collectorate',17),('Rajendra Nagar & Choithram Mandi',18),('Pipliyapala Regional Park',19),('Rau Circle & IPS Academy Area',20),('Ralamandal Wildlife Sanctuary',21),('Patalpani Waterfalls & Janapav Kuti',22)) as z(name,ord) where c.name='Indore' on conflict(city_id,name) do nothing;
insert into public.location_zones(city_id,name,display_order) select c.id,z.name,z.ord from public.cities c cross join (values ('Nagda Hills & Observatory Point',1),('Rajoda & Rajoda Hills Lake',2),('Industrial Area Phase 1 & 2',3),('Shankargarh Hills & Eco-Tourism Park',4),('Chamunda Nagar & Itawa Area',5),('Mata Tekri',6),('Dewas Ropeway Station & Tekri View Point',7),('Kushabhau Thakre Stadium',8),('Sayaji Gate & Lal Gate',9),('Pawar Chhatris',10),('Meetha Talab',11),('Dewas Bus Stand & Railway Station',12),('Bank Note Press (BNP) Campus & Colony',13),('Kshipra Dam & River Ghats',14)) as z(name,ord) where c.name='Dewas' on conflict(city_id,name) do nothing;
